blog/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$|^index', views.list_blog, name='index'),
    url(r'^view/(?P<slug>[-\w]+)', views.view_blog, name='view_blog'),
    url(r'^category/(?P<category>[\w]+)', views.list_blog_per_category, name='list_per_category'),
    url(r'^search', views.search_blog, name='search'),
    url(r'^add', views.add_blog, name='add_blog'),
    url(r'^edit', views.edit_blog, name='edit_blog'),
    url(r'^delete', views.delete_blog, name='delete_blog'),
    url(r'^about', TemplateView.as_view(template_name='blog/about.html'), name='about'),
    url(r'^comment/delete', views.delete_comment, name='del_comment'),
    url(r'^comment/add', views.add_comment, name='add_comment'),
    url(r'^get-categories', views.get_category_links, name='get_categories'),
]

my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import datetime


class Category(models.Model):
    """
    Model of categories.
    """
    content = models.CharField(max_length=50, primary_key=True)

    def __str__(self):
        return self.content

    def __repr__(self):
        return self.content


class Tag(models.Model):
    """
    Model of tags
    """
    name = models.CharField(max_length=50, primary_key=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name


class Blog(models.Model):
    """
    Model of blog articles.
    """
    author = models.ForeignKey(User)
    title = models.CharField(max_length=256)
    slug = models.SlugField(unique=True)
    content = models.CharField(max_length=4096)
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(to=Tag, related_name='blogs', related_query_name='blog', blank=True)
    pub_date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.title

    def __repr__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    """
    Model of comments to blog articles.
    """
    author = models.ForeignKey(User)
    content = models.CharField(max_length=4096)
    topic = models.ForeignKey(Blog, related_name='comments')
    reply_to = models.ForeignKey('self', null=True, blank=True, related_name='replies')
    pub_date = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ['pub_date']

    @classmethod
    def list_per_blog(cls, blog_pk):
        """
        Return the comments related to a blog article with the given pk.
        The comments that reply other comments will be added with an additional attribute reply_to_author, 
        which is the author of the comment replied.
        :param blog_pk: the pk of the blog article
        :return: the list of comments related to the blog article
        """
        comments = Comment.objects.select_related('reply_to').filter(topic=blog_pk)
        for comment in comments:
            if comment.reply_to is not None:
                comment.reply_to_author = comment.reply_to.author
        return comments

blog/forms.py
from django.forms import ModelForm, CharField
from django.forms.widgets import Textarea, HiddenInput

from .models import Comment, Blog


class CommentForm(ModelForm):
    def __init__(self, data=None, instance=None):
        if instance is not None:
            if instance.reply_to is not None:
                self.reply_to_author = Comment.objects.get(pk=instance.reply_to).author
        super(CommentForm, self).__init__(data=data, instance=instance)

    reply_to_author = CharField(max_length=50, required=False, widget=HiddenInput())

    class Meta:
        model = Comment
        fields = ['content', 'topic', 'reply_to', 'reply_to_author']
        widgets = {
            'content': Textarea(attrs={'cols': 60, 'rows': 5, 'class': 'form-control', 'style': "width: 60%"}),
            'topic': HiddenInput(), 'reply_to': HiddenInput(attrs={'required': False})}
        labels = {'content': 'Leave a comment'}


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', "category"]
        widgets = {'content': Textarea({'cols': 80, 'rows': 15})}

blog/views.py
import logging
import itertools
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils.translation import ugettext as _
from django.utils.text import slugify
from django.views.decorators.http import require_POST, require_GET
from django.db.models import Q
from django.http.response import JsonResponse

from .forms import CommentForm, BlogForm
from .models import Blog, Comment, Tag, Category
from .settings import BLOGS_PER_PAGE

logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger(__name__)


def list_blog(request):
    blog_list = Blog.objects.all()
    return _render_paged_blog_list(request, blog_list, 'Blogs')


def list_blog_per_category(request, category):
    blog_list = Blog.objects.filter(category=category)
    return _render_paged_blog_list(request, blog_list, 'Blogs of Category \'' + category + '\'')


def view_blog(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    comment_list = Comment.list_per_blog(blog.pk)
    return render(request, 'blog/view.html',
                  context={'blog': blog, 'comments': comment_list, 'comment_form': CommentForm()})


@login_required()
def add_blog(request):
    if not request.user.groups.filter(name='authors'):
        return render(request, 'blog/error.html', {'error': _('Insufficient privilege!'), 'message': _(
            'Insufficient privilege! Please contact administrator!')})
    if request.method == 'POST':
        parameters = request.POST
        log.debug(parameters)
        tags = parameters['tags'].split(',')
        tag_instances = []
        for tag in tags:
            try:
                tag_instances.append(Tag.objects.get(name=tag))
            except Tag.DoesNotExist:
                instance = Tag(name=tag)
                instance.save()
                tag_instances.append(instance)
        blog_form = BlogForm(parameters)
        if blog_form.is_valid():
            blog = blog_form.save(commit=False)
            blog.author = request.user
            slug_prefix = slugify(blog.title)
            slug = slug_prefix
            for i in itertools.count(1):
                if not Blog.objects.filter(slug=slug).exists():
                    break
                slug = "%s-%d" % (slug_prefix, i)
            blog.slug = slug
            blog.save()
            blog.tags.add(*tag_instances)
            blog.save()
            return redirect('blog:view_blog', slug=slug)
    else:
        return render(request, 'blog/add.html', {'categories': Category.objects.all()})


@login_required
@permission_required('blog.change_blog')
def edit_blog(request):
    if request.method == 'POST':
        parameters = request.POST
        blog = Blog.objects.get(pk=parameters.get('blog_id'))
        if request.user != blog.author:
            return render(request, 'blog/error.html', {'error': _('Insufficient privilege!'), 'message': _(
                'Insufficient privilege! Please contact administrator!')})
        tags = parameters['tags'].split(',')
        tag_instances = []
        for tag in tags:
            try:
                tag_instances.append(Tag.objects.get(name=tag))
            except Tag.DoesNotExist:
                instance = Tag(name=tag)
                instance.save()
                tag_instances.append(instance)
        blog_form = BlogForm(parameters, instance=blog)
        if blog_form.is_valid():
            blog_modified = blog_form.save(commit=False)
            slug_prefix = slugify(blog.title)
            slug = slug_prefix
            for i in itertools.count(1):
                if not Blog.objects.filter(slug=slug).exists():
                    break
                slug = "%s-%d" % (slug_prefix, i)
            blog_modified.slug = slug
            blog_modified.tags.add(*tag_instances)
            blog_modified.save()
            return redirect(reverse('blog:view_blog', args=(blog_modified.slug,)))
    else:
        blog = Blog.objects.get(pk=request.GET.get('blog_id'))
        blog_form = BlogForm(instance=blog)
        tag_str = ','.join(tag.name for tag in blog.tags.all())
        return render(request, 'blog/add.html',
                      {'blog_form': blog_form, 'categories': Category.objects.all(), 'blog_id': blog.pk,
                       'tags': tag_str})


@login_required
@permission_required('blog.delete_blog')
def delete_blog(request):
    if request.method == 'post':
        blog_id = request.POST.get('blog_id')
    else:
        blog_id = request.GET.get('blog_id')
    if blog_id is None or not Blog.objects.filter(pk=blog_id).exists():
        return redirect(reverse('blog:error', kwargs={'error': _('The required blog does not exist'),
                                                      'message': _(
                                                          'The required blog does not exist! Please perform the operation through the valid pages')}))
    blog = Blog.objects.get(pk=blog_id)
    if request.user != blog.author:
        return redirect(reverse('blog:error', kwargs={'error': _('Insufficient Previlige'),
                                                      'message': _(
                                                          'You are not the author of the blog to delete. Cannot perform the deletion!')}))
    blog.delete()
    return redirect(reverse('blog:index'))


@require_GET
def search_blog(request):
    parameters = request.GET
    q_chain = Q()
    for key in parameters.keys():
        if key == 'keyword':
            q_chain &= Q(title__icontains=parameters['keyword']) | Q(tags=parameters['keyword'])
        elif key == 'author':
            q_chain &= Q(author__username=parameters['author'])
        else:
            q_chain &= Q(**{key: parameters[key]})
    blog_list = Blog.objects.filter(q_chain).distinct()
    return render(request, 'blog/index.html', {'blog_list': blog_list, 'title': 'Search Results'})


@require_GET
@permission_required('blog.delete_comment')
def delete_comment(request):
    Comment.objects.get(pk=request.GET.get('comment')).delete()
    return redirect(request.GET.get('next'))


@require_POST
@permission_required('blog.add_comment')
def add_comment(request):
    comment_form = CommentForm(request.POST)
    author = request.user
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.author = author
        comment.save()
        return redirect(request.META['HTTP_REFERER'])
    else:
        raise Exception(comment_form.errors)


def get_category_links(request):
    data = {}
    for c in Category.objects.all():
        data[c.content] = reverse('blog:list_per_category', args=[c.content])
    return JsonResponse(data)


def _render_paged_blog_list(request, blog_list, title):
    paginator = Paginator(blog_list, BLOGS_PER_PAGE)
    page = request.GET.get('page')
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)
    return render(request, 'blog/index.html',
                  context={'blog_list': blogs, 'title': title})

blog/templates/blog/add.html
{% extends 'blog/base.html' %}
{% load staticfiles i18n %}
{% block title %}Adding New Blog{% endblock %}
{% block extra_js %}
    <script src="{% static 'blog/js/bootstrap-tagsinput.min.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="well" style="margin: 5%">
        <form action="{{ request.path }}" method="post" id="blog-form" class="clearfix">
            {% csrf_token %}
            <div class="form-group col-md-12">
                <label class="text-muted">Title</label>
                <input class="form-control" name="title" id="id_title" type="text" maxlength="50"
                       value="{{ blog_form.title.value }}" required>
            </div>
            <div class="form-group col-md-6"><label class="text-muted">Category</label>
                <select class="select form-control" name="category" id="id_category" required>
                    <option value="" class="text-muted">Please select...</option>
                    {% for category in categories %}
                    <option value="{{ category.pk }}"{% ifequal blog_form.category.value category.content %} selected="selected"{% endifequal %}>{{ category.content }}</option>
                    {% endfor %}</select></div>
            <div class="form-group col-md-6"><label class="text-muted">Tags</label>
                <input type="text" data-role="tagsinput" id="id_tags" name="tags" class="form-control"
                       value="{{ tags }}">
            </div>
            <div class="form-group col-md-12"><label class="text-muted">Content</label>
                <textarea name="content" rows="15" cols="80" class="form-control"
                          required>{{ blog_form.content.value }}</textarea>
            </div>
            <input type="hidden" value="{{ user }}" name="author" id="id_author">
            <input type="hidden" value="{{ blog_id }}" name="blog_id" id="id_blog_id">
            <div class="form-group col-md-2 pull-right">
                <button type="submit" id="submit" class="form-control btn-sm text-info glyphicon glyphicon-ok">OK
                </button>
            </div>
        </form>
    </div>
{% endblock %}
{#{% block extra_script %}#}
{#    <script>#}
{#        $(document).ready(function () {#}
{#            $('#submit').on('click', function (event) {#}
{#                event.preventDefault();#}
{#                var element = $('#id_tags');#}
{#                document.getElementById('id_tags').value = $('#id_tags').tagsinput('items');#}
{#                $('#blog-form').submit();#}
{#            });#}
{#            $('#id_tags').on('keypress', function (event) {#}
{#                if (event.keyCode === 13) {#}
{#                    event.keyCode = 188;#}
{#                    event.preventDefault();#}
{#                }#}
{#            }).tagsinput({#}
{#                confirmKeys: [13, 188]#}
{#            });#}
{#        });#}
{#    </script>#}
{#{% endblock %}#}

blog/templates/blog/base.html
{% load staticfiles i18n chinesename_tags %}
{% now 'Y' as now_year %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Blog of Littsler Li">
    <meta name="author" content="Littsler Li">

    <title>{% block title %}{% endblock %} | Littsler Li</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'blog/css/blog-post.css' %}" rel="stylesheet">

    <!-- Fontawsome CSS -->
    <link href="{% static 'blog/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'icons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'icons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'icons/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'icons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <style type="text/css">a:hover {
        text-decoration: none
    }</style>

    <!-- jQuery -->
    <script src="{% static 'blog/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    {% block extra_css %}{% endblock %}
    {% block extra_js %}{% endblock %}
    {% block extra_script %}{% endblock %}
    <script>
        $(document).ready(function () {
            $.getJSON("{% url 'blog:get_categories' %}", function (data) {
                $.each(data, function (name, url) {
                    {#                    var li_node = document.createElement("li");#}
                    {#                    var a_node = document.createElement("a");#}
                    {#                    a_node.href = url;#}
                    {#                    a_node.text = name;#}
                    {#                    li_node.appendChild(a_node);#}
                    $('#list_categories').append(
                        $("<li></li>").append(
                            $("<a></a>").attr("href", url).text(name)
                        )
                    );
                });
            });
        });
    </script>
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog:index' %}">{% trans 'Home' %}</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'blog:index' %}">{% trans 'Blog' %}</a>
                </li>
                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle"
                       id="dropdown_categories">{% trans 'Categories' %}<span
                            class="caret"></span></a>
                    <ul class="dropdown-menu navbar-nav" id="list_categories">
                    </ul>
                </li>
                <li>
                    <a href="{% url 'blog:about' %}">{% trans 'About Me' %}</a>
                </li>
                {% if not user.is_anonymous and perms.blog.add_blog %}
                    <li>
                        <a href="{% url 'blog:add_blog' %}">{% trans 'Write New Blogs' %}</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <form role="search" class="navbar-form" action="{% url 'blog:search' %}">
                        <div class="form-group">
                            <input class="form-control input-sm" placeholder="Search" type="text" name="keyword">
                        </div>
                        <button type="submit" class="btn btn-sm"><span class="glyphicon glyphicon-search"></span>
                        </button>
                    </form>
                </li>
                <li><a href="https://github.com/littsler" style="padding-top: 10px; padding-bottom: 10px"><img
                        src="{% static 'icons/github-ico.png' %}" height="30"
                        width="30" align="bottom"></a></li>
                <li>
                    {% if user.is_anonymous %}
                        <li>
                            <a href="{% url 'login' %}?next={{ request.get_full_path|urlencode }}">{% trans 'Log in' %}</a>
                        </li>
                    {% else %}
                        <div class="dropdown">
                            <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                {{ user|chinese_name }}<span class="caret"></span></a>
                                <ul class="dropdown-menu navbar-nav">
                                    <li>
                                        <a href="{% url 'logout' %}?next={{ request.get_full_path|urlencode }}">{% trans 'Log out' %}</a>
                                    </li>
                                </ul>
                            </li>
                        </div>
                    {% endif %}
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Page Content -->
<div class="container" id="container" style="min-height: 100vh;display: flex;flex-direction: column">
    <div class="row modal-content"
         style="flex: 1;width: 100%; padding-left: 5%; padding-right: 5%; padding-bottom: 100px">
        {% block content %}
        {% endblock %}
    </div>
    <hr>

    <!-- Footer -->
    <footer class="navbar-collapse navbar-fixed-bottom navbar-default">
        <nav>
            <div align="middle">
                <span class="navbar-text" style="width: 100%; align-self: center">Copyright &copy; Littsler Li
                    {% if now_year != '2016' %}2016-{% now 'Y' %}{% else %}
                        2016{% endif %}</span>
            </div>
        </nav>
        <!-- /.row -->
    </footer>

</div>
<!-- /.container -->

</body>

</html>

blog/templates/blog/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

blog/templates/blog/error.html
{% extends 'blog/base.html' %}
{% load staticfiles i18n %}
{% block title %}Error{% endblock %}
{% block content %}
    <div align="middle">
        <p>
            <span class="text-warning text-center h3">
                <img src="{% static 'svg/exclamation-sign-in-a-circle.svg' %}" height="30" width="30">
                Error!{{ error }}
            </span>
        </p>
        <p>
            <span class="text-info text-center h4">
                {{ message }}
            </span>
        </p>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load staticfiles i18n chinesename_tags mathfilters %}
{% block title %} {{ title }}{% endblock %}
{% block content %}
    {% for blog in blog_list %}
        <section class="well-lg">
            <h2><a href="{% url 'blog:view_blog' slug=blog.slug %}">{{ blog.title }}</a></h2>
            <code class="text-muted glyphicon glyphicon-pencil">
                <a href="{% url 'blog:search' %}?author={{ blog.author }}">
                    {{ blog.author|chinese_name }}
                </a>
            </code>
            <hr style="border: none; margin: 10px">
            <code class="text-muted glyphicon glyphicon-time">
                {{ blog.pub_date|date:'Y-m-d' }}
            </code>
            <hr style="border: none; margin: 15px">
            <p>
                {{ blog.content|slice:":256"|linebreaksbr }}{% if blog.content|length > 256 %}...{% endif %}</p>
            <hr style="border: none; margin: 15px">
            <code>
                <a class="text-info btn-xs" href="{% url 'blog:view_blog' slug=blog.slug %}">
                    Read More...
                </a>
            </code>
            <hr style="border: none; margin: 20px">
            <code><a class="icon-comments text-success" href="{% url 'blog:view_blog' slug=blog.slug %}#comments">
                ({{ blog.comments.count }})
            </a></code>
            <hr style="border: none; margin: 20px">
            <span>
            {% for tag in blog.tags.all %}
                <code><a class="glyphicon glyphicon-tag text-muted"
                         href="{% url 'blog:search' %}?tags={{ tag.name }}">{{ tag.name }}</a></code>
            {% endfor %}
            </span>
            <hr>
        </section>
    {% endfor %}
    <div>
        {% if blog_list.has_previous %}
            <a class="btn glyphicon glyphicon-arrow-left col-lg-2"
               href="{{ request.path }}?page={{ blog_list.previous_page_number }}">
                Prev
            </a>{% endif %}
        <div class="col-lg-8"></div>
        {% if blog_list.has_next %}
            <a class="btn glyphicon glyphicon-arrow-right col-lg-2"
               href="{{ request.path }}?page={{ blog_list.next_page_number }}">
                Next
            </a>{% endif %}
    </div>
{% endblock %}

blog/templates/blog/view.html
{% extends 'blog/base.html' %}
{% load staticfiles i18n chinesename_tags %}
{% block title %}{{ blog.title }}{% endblock %}
{% block content %}
    <section class="form-group">
        <h2 class="text-primary">{{ blog.title }}</h2>
        <hr style="margin: 50px; border: none">
        <small class="text-primary">
            <code class="glyphicon glyphicon-pencil">
                <a href="{% url 'blog:search' %}?author={{ blog.author }}" class="h5 text-info">
                    {{ blog.author|chinese_name }}
                </a>
            </code>
        </small>
        <hr style="border: none; margin: 10px">
        <small class="text-muted">
            <code class="glyphicon glyphicon-time">
                {{ blog.pub_date|date:'Y-m-d' }}</code>
        </small>
        {% ifequal user blog.author %}
            <hr style="border: none; margin: 10px">
            <div class="text-muted">
                <code class="glyphicon glyphicon-edit">
                    <a href="{% url 'blog:edit_blog' %}?blog_id={{ blog.pk }}" class="h5 text-info">
                        {% trans 'Edit' %}
                    </a>
                </code>
                <code class="glyphicon glyphicon-remove">
                    <a href="{% url 'blog:delete_blog' %}?blog_id={{ blog.pk }}" class="h5 text-info confirmation">
                        {% trans 'Delete' %}
                    </a>
                </code>
            </div>
        {% endifequal %}
        <hr style="border: none; margin: 30px">
        <p>
        <div class="modal-body">{{ blog.content|linebreaksbr }}</div>
        <hr style="border: none; margin: 30px">
        <span>
            {% for tag in blog.tags.all %}
                <a class="glyphicon glyphicon-tag text-muted"
                   href="{% url 'blog:search' %}?tags={{ tag.name }}">{{ tag.name }}</a>
            {% endfor %}
        </span>
        <hr style="margin: 50px">
        <div id="comments">
            {% for comment in comments %}
                <div class="media well-lg" style="padding-right: 40%">
                    <div class="text-primary h5"><a class="text-primary h5"
                                                    href="{% url 'blog:search' %}?author={{ comment.author }}">{{ comment.author|chinese_name }}</a>
                        {% if comment.reply_to != None %}
                            <small class="text-muted"> replied to</small>
                            <a href="{% url 'blog:search' %}?author={{ comment.reply_to_author }}"
                               class="text-primary h5">{{ comment.reply_to_author|chinese_name }}</a>
                        {% endif %}
                        {{ comment.pub_date|date:'Y-m-d H:i' }}</div>
                    <hr style="border: none">
                    <div class="text-info media-body">
                        {{ comment.content|linebreaksbr }}
                    </div>
                    <div class="media-bottom pull-right">
                        {% if perms.blog.add_comment %}
                            <a href="#comment_form"
                               onclick="set_reply('{{ comment.pk }}','{{ comment.author }}','{{ comment.author|chinese_name }}');"
                               style="padding-right: 20px">Reply</a>
                        {% endif %}
                        {% ifequal user comment.author %}
                            <a href="{% url 'blog:del_comment' %}?comment={{ comment.pk }}&next={{ request.get_full_path|urlencode }}">Delete</a>
                        {% endifequal %}
                    </div>
                </div>
                <hr style="border: none; margin: 25px">
            {% endfor %}
        </div>
        {% if perms.blog.add_comment %}
            <hr>
            <form class="text-muted well-lg" id="comment_form" name="comment_form" method="post" role="form"
                  action="{% url 'blog:add_comment' %}">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <div class="pull-right" style="padding-right: 40%">
                    <button type="submit" name="submit" class="glyphicon glyphicon-upload btn btn-xs">
                        Submit Comment
                    </button>
                </div>
            </form>
        {% endif %}
    </section>
{% endblock %}
{% block extra_script %}
    <script>
        $(document).ready(function () {
            $('#id_topic').val({{ blog.pk }});
            $('.confirmation').on('click', function () {
                return confirm('Are you sure?');
            });
        });

        function set_reply(comment_id, author, author_name) {
            $('#id_reply_to').val(comment_id);
            $('#id_reply_to_author').val(author);
            var element = $('label[for=id_content]');
            element.text(element.text() + " Reply to " + author_name);
        }
    </script>
{% endblock %}